# Use the full Node.js image instead of Alpine
FROM node:22

# Set the working directory
WORKDIR /app

# Copy package.json to install dependencies
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
CMD ["npm", "run", "dev"]